### ISSUE TITLE
why do you change the range before the dct transform？

### ISSUE THREAD

**Issue by xiatutu** [typ-AhmedSleem/JPEG#1]
`# Shift all channels pixels to be in range -128 to 127
    sY = func.shiftChannel(y).astype(np.float32)
    sCb = func.shiftChannel(cb).astype(np.float32)
    sCr = func.shiftChannel(cr).astype(np.float32)`
![image](https://github.com/typ-AhmedSleem/JPEG/assets/33248045/2c268eef-8fdd-43eb-920f-9d0a748b23be)

**Comment by typ-AhmedSleem** [comment]
Sorry for the late response,

Because we want to center the pixel value around the zero, making **-128 absolute black** and **127 absolute white**.
